const std = @import("std");

const Block = @import("Chunk").Block;
const Chunk = @import("Chunk").Chunk;

//TODO handle structures, they get regenerated by fromBlocks and fromOneBlock
pub const Region = struct {
    pub const Size = 8;
    const version: std.SemanticVersion = .{ .major = 0, .minor = 0, .patch = 0 };

    const ChunkHeader = packed struct {
        memEncoding: @typeInfo(Chunk.BlockEncoding).@"union".tag_type.?,
        metdata: packed union {
            oneBlock: Block,
            none: u0,
        },
    };

    pub const ChunkSectionEncoding = enum(u8) {
        Raw = 0,
    };

    const Header = packed struct {
        pub const MagicBytes = "terrafinityregion";
        version: packed struct {
            major: u16,
            minor: u16,
            patch: u16,
        },
        chunkSectionEncoding: ChunkSectionEncoding,
    };

    pub const FullHeader = struct {
        header: Header,
        chunkHeader: [Size][Size][Size]?ChunkHeader,

        fn fromChunks(chunkSectionEncoding: ChunkSectionEncoding, chunks: [Size][Size][Size]?*Chunk) !FullHeader {
            const header: Header = .{
                .version = .{ .major = version.major, .minor = version.minor, .patch = version.patch },
                .chunkSectionEncoding = chunkSectionEncoding,
            };
            var flatChunkHeader: [Size * Size * Size]?ChunkHeader = undefined;
            const flatChunks: *const [Size * Size * Size]?*Chunk = @ptrCast(&chunks);
            for (flatChunks, &flatChunkHeader) |chunk, *headerPtr| {
                var chunkHeader: ?ChunkHeader = null;
                if (chunk) |c| {
                    c.lock.lockShared();
                    chunkHeader = .{
                        .memEncoding = c.blocks,
                        .metdata = switch (c.blocks) {
                            .oneBlock => .{ .oneBlock = c.blocks.oneBlock },
                            else => .{ .none = 0 },
                        },
                    };
                    c.lock.unlockShared();
                }
                headerPtr.* = chunkHeader;
            }
            return .{ .header = header, .chunkHeader = @bitCast(flatChunkHeader) };
        }
    };

    ///fully overwrites the Region with the provided chunks, destroys any existing region data. chunks may not be all null
    pub fn write(writer: *std.Io.Writer, chunkSectionEncoding: ChunkSectionEncoding, chunks: [Size][Size][Size]?*Chunk) !void {
        std.debug.assert(!std.meta.eql(chunks, @splat(@splat(@splat(null)))));
        try writeHeader(writer, try .fromChunks(chunkSectionEncoding, chunks));
        try writeChunks(writer, chunkSectionEncoding, chunks);
    }

    ///merges the Region with the provided chunks, replaces existing if the same chunk is provided. chunks may not be all null
    pub fn merge(reader: *std.Io.Reader, writer: *std.Io.Writer, chunkSectionEncoding: ChunkSectionEncoding, chunks: [Size][Size][Size]?*Chunk) !void {
        std.debug.assert(!std.meta.eql(chunks, @splat(@splat(@splat(null)))));
        const header = readHeader(reader) catch null;
        var mergeheader = try FullHeader.fromChunks(chunkSectionEncoding, chunks);
        if (header != null) {
            for (@as(*const [Size * Size * Size]?ChunkHeader, @ptrCast(&header.?.chunkHeader)), @as(*[Size * Size * Size]?ChunkHeader, @ptrCast(&mergeheader.chunkHeader))) |h1, *h2| {
                if (h2.* == null and h1 != null) h2.* = h1;
            }
        }
        try writeHeader(writer, mergeheader);
        try mergeChunks(reader, writer, chunkSectionEncoding, mergeheader.chunkHeader, chunks);
    }

    fn writeHeader(writer: *std.Io.Writer, fullHeader: FullHeader) !void {
        try writer.writeSliceEndian(u8, Header.MagicBytes, .little);
        try writer.writeStruct(fullHeader.header, .little);
        try writer.writeSliceEndian(?ChunkHeader, @ptrCast(&fullHeader.chunkHeader), .little);
    }

    ///Region file is assumed to be valid
    pub fn readHeader(reader: *std.Io.Reader) !FullHeader {
        var magicBytes: [17]u8 = undefined;
        try reader.readSliceEndian(u8, &magicBytes, .little);
        const header = try reader.takeStruct(Header, .little);
        if (!std.meta.eql(magicBytes, Header.MagicBytes.*)) return error.InvalidFileType;
        var chunkHeader: [Size][Size][Size]?ChunkHeader = undefined;
        try reader.readSliceEndian(?ChunkHeader, @ptrCast(&chunkHeader), .little);
        return .{ .header = header, .chunkHeader = chunkHeader };
    }

    fn mergeChunks(reader: *std.Io.Reader, writer: *std.Io.Writer, chunkSectionEncoding: ChunkSectionEncoding, chunkHeader: [Size][Size][Size]?ChunkHeader, chunks: [Size][Size][Size]?*Chunk) !void {
        std.debug.assert(chunkSectionEncoding == .Raw);

        const encodedWriter: *std.Io.Writer = writer; //TODO compression
        const encodedReader: *std.Io.Reader = reader;
        const flatChunks: *const [Size * Size * Size]?*Chunk = @ptrCast(&chunks);
        const flatChunkHeader: *const [Size * Size * Size]?ChunkHeader = @ptrCast(&chunkHeader);

        for (flatChunks, flatChunkHeader) |chunk, chunkheader| {
            if (chunk) |c| {
                switch (c.blocks) {
                    .blocks => {
                        const flatblockArray: *const [Chunk.ChunkSize * Chunk.ChunkSize * Chunk.ChunkSize]Block = @ptrCast(c.blocks.blocks);
                        try encodedWriter.writeSliceEndian(Block, flatblockArray, .little);
                    },
                    .oneBlock => {},
                }
            } else if (chunkheader) |h| {
                switch (h.memEncoding) {
                    .blocks => {
                        try encodedReader.streamExact(encodedWriter, Chunk.ChunkSize * Chunk.ChunkSize * Chunk.ChunkSize * @sizeOf(Block));
                    },
                    .oneBlock => {},
                }
            }
        }
        try encodedWriter.flush();
    }

    fn writeChunks(writer: *std.Io.Writer, chunkSectionEncoding: ChunkSectionEncoding, chunks: [Size][Size][Size]?*Chunk) !void {
        std.debug.assert(chunkSectionEncoding == .Raw);
        const encodedWriter: *std.Io.Writer = writer; //TODO compression

        const flatChunks: *const [Size * Size * Size]?*Chunk = @ptrCast(&chunks);

        for (flatChunks) |chunk| {
            if (chunk) |c| {
                switch (c.blocks) {
                    .blocks => {
                        const flatblockArray: *const [Chunk.ChunkSize * Chunk.ChunkSize * Chunk.ChunkSize]Block = @ptrCast(c.blocks.blocks);
                        try encodedWriter.writeSliceEndian(Block, flatblockArray, .little);
                    },
                    .oneBlock => {},
                }
            }
        }
        try encodedWriter.flush();
    }

    ///loads all block encodings in the region with the allocator, reader pos must be after the header
    ///Region file is assumed to be valid
    pub fn loadEncodings(reader: *std.Io.Reader, fullHeader: FullHeader, allocator: std.mem.Allocator) ![Size][Size][Size]?Chunk.BlockEncoding {
        const encodedReader: *std.Io.Reader = reader;
        var flatEncodings: [Size * Size * Size]?Chunk.BlockEncoding = @splat(null);
        var blocks: [Chunk.ChunkSize * Chunk.ChunkSize * Chunk.ChunkSize]Block = undefined;
        for (&flatEncodings, @as([Size * Size * Size]?ChunkHeader, @bitCast(fullHeader.chunkHeader))) |*encoding, header| {
            if (header) |h| {
                switch (h.memEncoding) {
                    .blocks => {
                        try encodedReader.readSliceEndian(Block, &blocks, .little);
                        encoding.* = try Chunk.BlockEncoding.fromBlocks(@ptrCast(&blocks), allocator);
                    },
                    .oneBlock => {
                        encoding.* = Chunk.BlockEncoding{ .oneBlock = h.metdata.oneBlock };
                    },
                }
            }
        }
        return @bitCast(flatEncodings);
    }
};

test "write" {
    var writeBuf: [65536]u8 = undefined;
    var readBuf: [65536]u8 = undefined;

    const file = std.fs.cwd().openFile("test.tfr", .{ .mode = .read_write, .lock = .exclusive }) catch |err| switch (err) {
        error.FileNotFound => try std.fs.cwd().createFile("test.tfr", .{ .read = true }),
        else => return err,
    };
    defer file.close();
    defer file.unlock();
    var writer = file.writer(&writeBuf);
    var reader = file.reader(&readBuf);

    var blocks: [Chunk.ChunkSize][Chunk.ChunkSize][Chunk.ChunkSize]Block = @splat(@splat(@splat(Block.dirt)));

    const tchunk = try Chunk.FromBlocks(&blocks, std.testing.allocator);

    const tchunk2 = try Chunk.FromBlocks(&blocks, std.testing.allocator);

    var chunks: [Region.Size][Region.Size][Region.Size]?*Chunk = @splat(@splat(@splat(null)));

    chunks[std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)][std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)][std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)] = tchunk2;
    chunks[0][5][0] = tchunk2;
    chunks[0][0][2] = tchunk2;

    chunks[0][2][0] = tchunk;
    chunks[std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)][std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)][std.crypto.random.intRangeAtMost(usize, 0, Region.Size - 1)] = tchunk;

    defer std.testing.allocator.destroy(tchunk);
    defer tchunk.free(std.testing.allocator);
    defer std.testing.allocator.destroy(tchunk2);
    defer tchunk2.free(std.testing.allocator);
    try Region.write(&reader.interface, &writer.interface, .Raw, chunks);

    try file.setEndPos(writer.pos);
}

test "read" {
    var readBuf: [65536]u8 = undefined;
    const file = try std.fs.cwd().openFile("testWorld/RegionStorage/{ -1, -1, -1 }.tfr", .{ .mode = .read_only, .lock = .exclusive });
    defer file.close();
    defer file.unlock();
    var reader = file.reader(&readBuf);
    const h = try Region.readHeader(&reader.interface);
    const o = try Region.loadAllOneBlockChunks(h, std.testing.allocator);
    const c = try Region.loadAllBlockChunks(&reader.interface, h, std.testing.allocator);

    for (o) |x| {
        for (x) |y| {
            for (y) |z| {
                if (z != null) {
                    std.debug.print("h: {any}\n", .{z.?.blocks.oneBlock});
                    z.?.free(std.testing.allocator);
                    std.testing.allocator.destroy(z.?);
                } else {
                    std.debug.print("h: null\n", .{});
                }
            }
        }
    }

    for (c) |x| {
        for (x) |y| {
            for (y) |z| {
                if (z != null) {
                    //     std.debug.print("h: {any}\n", .{z.?.blocks.blocks});
                    z.?.free(std.testing.allocator);
                    std.testing.allocator.destroy(z.?);
                }
            }
        }
    }
}
