#version 460 core
#extension GL_ARB_gpu_shader_int64 : require

layout(local_size_x = 64) in;

struct InputChunk {
    vec4 absolute_position;
    uint64_t address;
    float scale;
    uint face_count;
    uint is_transparent;
};

struct ChunkData {
    vec4 absolute_position;
    vec4 relative_position;
    uint64_t address;
    float scale;
};

struct DrawIndirectCommand {
    uint vertex_count;
    uint instance_count;
    uint first_vertex;
    uint first_instance;
};

layout(std430, binding = 0) readonly buffer InputBuffer {
    InputChunk candidate_chunks[];
};

layout(std430, binding = 1) writeonly buffer OutputIndirectBuffer {
    DrawIndirectCommand out_indirect[];
};

layout(std430, binding = 2) writeonly buffer OutputChunkBuffer {
    ChunkData out_chunks[];
};

layout(std430, binding = 3) buffer CountBuffer {
    uint opaque_count;
    uint transparent_count;
};

layout(push_constant) uniform PushConsts {
    vec4 planes[6];
    vec4 player_pos;
    uint total_candidates;
    uint draw_capacity;
} pc;

bool boxInFrustum(vec3 bmin, vec3 bmax) {
    for (int i = 0; i < 6; i++) {
        vec4 plane = pc.planes[i];
        if (dot(plane.xyz, mix(bmin, bmax, greaterThan(plane.xyz, vec3(0.0)))) + plane.w < 0.0) return false;
    }
    return true;
}

void main() {
    uint g_idx = gl_GlobalInvocationID.x;
    if (g_idx >= pc.total_candidates) return;

    InputChunk chunk = candidate_chunks[g_idx];
    if (chunk.face_count == 0u) return;

    vec3 relative_pos = chunk.absolute_position.xyz - pc.player_pos.xyz;
    float size = chunk.scale * 32.0;
    if (!boxInFrustum(relative_pos, relative_pos + vec3(size))) return;

    uint idx;
    if (chunk.is_transparent == 0u) {
        idx = atomicAdd(opaque_count, 1u);
    } else {
        idx = atomicAdd(transparent_count, 1u);
    }
    if (idx >= pc.draw_capacity) return;

    uint out_idx = idx + (chunk.is_transparent * pc.draw_capacity);
    out_indirect[out_idx] = DrawIndirectCommand(
        chunk.face_count * 6u,
        1u,
        0u,
        out_idx
    );
    out_chunks[out_idx] = ChunkData(
        chunk.absolute_position,
        vec4(relative_pos, 1.0),
        chunk.address,
        chunk.scale
    );
}
